site_name: simple-action-pipeline
repo_url: https://github.com/antarctica/simple-action-pipeline/
theme: readthedocs
plugins: 
  - search
  - mkdocstrings
  - include-markdown:
      rewrite_relative_urls: true

nav:
  - Home: index.md
  - implementation.md
  - installation.md
  - using.md
  - example.md
  - how-sap-works.md
  - development.md